### ISSUE TITLE
Build on Debian 9?

### ISSUE THREAD

**Issue by djzort** [salviati/xfsr#1]
I have cloned your code and installed what i believe are the right libraries:
`apt-get install xfslibs-dev`

however compiling fails:
```

dean@cliffjumper:~/git/xfsr$ make
gcc -lm -I ./include -O -ggdb -Wall -DBUILDPROGLS xfsr-ls.c xfsr.c xfsr-dump.c -o xfsr-ls
In file included from xfsr-ls.c:22:0:
xfsr.h:28:11: fatal error: libxfs.h: No such file or directory
 # include <libxfs.h>
           ^~~~~~~~~~
compilation terminated.
In file included from xfsr.c:22:0:
xfsr.h:28:11: fatal error: libxfs.h: No such file or directory
 # include <libxfs.h>
           ^~~~~~~~~~
compilation terminated.
In file included from xfsr-dump.c:22:0:
xfsr.h:28:11: fatal error: libxfs.h: No such file or directory
 # include <libxfs.h>
           ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:7: xfsr-ls] Error 1
dean@cliffjumper:~/git/xfsr$ apt-cache search libxfs
dean@cliffjumper:~/git/xfsr$ make
gcc -lm -I ./include -O -ggdb -Wall -DBUILDPROGLS xfsr-ls.c xfsr.c xfsr-dump.c -o xfsr-ls
In file included from xfsr-ls.c:22:0:
xfsr.h:28:11: fatal error: libxfs.h: No such file or directory
 # include <libxfs.h>
           ^~~~~~~~~~
compilation terminated.
In file included from xfsr.c:22:0:
xfsr.h:28:11: fatal error: libxfs.h: No such file or directory
 # include <libxfs.h>
           ^~~~~~~~~~
compilation terminated.
In file included from xfsr-dump.c:22:0:
xfsr.h:28:11: fatal error: libxfs.h: No such file or directory
 # include <libxfs.h>
           ^~~~~~~~~~
compilation terminated.

```

there is no libxfs.h file in the xfslibs-dev package.

perhaps this file has been renamed?

**Comment by salviati** [comment]
This was written against xfsprogs-2.9.8, so it may be more than a file rename, I expect the compatibility is also broken since then. It should work using headers from [xfsprogs-2.9.8](https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/xfsprogs/2.9.8-1/xfsprogs_2.9.8.orig.tar.gz) though.
